---
abstract: 'Build and install open-vcdiff, a binary diff/patch library'
author:
  - 'Doug Hoyte <doug@hcsw.org>'
build_requires: {}
configure_requires:
  Alien::Base: 0.003
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112620'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-OpenVcdiff
provides:
  Alien::OpenVcdiff:
    file: lib/Alien/OpenVcdiff.pm
    version: 0.100
requires:
  Alien::Base: 0
  File::ShareDir: 1.00
  perl: v5.8.1
resources:
  bugtracker: https://github.com/hoytech/Alien-OpenVcdiff/issues
  homepage: https://github.com/hoytech/Alien-OpenVcdiff
  license: http://apache.org/licenses/LICENSE-2.0
  repository: git://github.com/hoytech/Alien-OpenVcdiff.git
version: 0.100
